name: Build and Deploy Heal Link
on:
  push:
    branches: [main]
jobs:
  build-flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - name: Install dependencies
        run: cd Flutter/heal_link && flutter pub get
      - name: Analyze code
        run: cd Flutter/heal_link && flutter analyze
      - name: Run tests
        run: cd Flutter/heal_link && flutter test
      - name: Build APK
        run: cd Flutter/heal_link && flutter build apk --release
      - name: Build Web
        run: cd Flutter/heal_link && flutter build web --release
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: Flutter/heal_link/build/app/outputs/flutter-apk/app-release.apk
      - name: Upload Web artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: Flutter/heal_link/build/web
  deploy-app-distribution:
    runs-on: ubuntu-latest
    needs: build-flutter
    if: github.actor == 'Mahm0udbakir'
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v3
        with:
          name: app-release.apk
      - name: Deploy to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase appdistribution:distribute app-release.apk --app 1:383414444909:android:921a78a39e71e83a873064 --token "$FIREBASE_TOKEN"
  deploy-hosting:
    runs-on: ubuntu-latest
    needs: build-flutter
    if: github.actor == 'Mahm0udbakir'
    steps:
      - name: Download Web artifact
        uses: actions/download-artifact@v3
        with:
          name: web-build
          path: Flutter/heal_link/build/web
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --project heal-link0 --token "$FIREBASE_TOKEN"